[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
    -std=gnu99
    -I..
    -I../..

lib_deps =

[env:esp32-s3-usb-otg]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
    -std=gnu99
    -I..
    -I../..
board_build.arduino.usb_cdc = true
